### ISSUE TITLE
Use renovate instead of dependabot

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-sdk-js-tests#96]
**Is your feature request related to a problem? Please describe.**
Automated PRs are not posted for bumping versions related to security advisories in third-party dependencies.
The PRs have to be manually posted like https://github.com/aws-samples/aws-sdk-js-tests/pull/95

**Describe the solution you'd like**
Use [renovate](https://github.com/renovatebot/renovate) for automated dependency updates, as it supports Yarn v2.
The request to support Yarn v2 has been pending in dependabot repo since Aug 2019 at https://github.com/dependabot/dependabot-core/issues/1297, and several dependabot customers have been moving to RenovateBot.

**Describe alternatives you've considered**
* Switch to npm with limited workspaces support.
* Downgrade to yarn legacy.
* Explore pnpm.

**Comment by leakhand** [comment]
I want an example of how to connect with S3 with ARN role

**Comment by trivikr** [comment]
Renovate was set up.

Configuration: https://github.com/aws-samples/aws-sdk-js-tests/blob/4be2f9aebe97c2f710baa6b418bc519a9409acdb/.github/renovate.json
Example dashboard: https://github.com/aws-samples/aws-sdk-js-tests/issues/122
